server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
          filters:
           - name: CircuitBreaker
             args:
              name: RESTAURANT-SERVICE
              fallbackuri: /restaurantServiceFallBack
           - name: RequestRateLimiter
             args:
               '[redis-rate-limiter.replenishRate]': 1
               '[redis-rate-limiter.burstCapacity]': 1
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
           - name: CircuitBreaker
             args:
              name: ORDER-SERVICE
              fallbackuri: /orderServiceFallBack
           - name: RequestRateLimiter
             args:
               '[redis-rate-limiter.replenishRate]': 1
               '[redis-rate-limiter.burstCapacity]': 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
           - name: CircuitBreaker
             args:
              name: PAYMENT-SERVICE
              fallbackuri: /paymentServiceFallBack
           - name: RequestRateLimiter
             args:
               '[redis-rate-limiter.replenishRate]': 1
               '[redis-rate-limiter.burstCapacity]': 1
        - id: DELIVERY-SERVICE
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/deliveries/**
          filters:
           - name: CircuitBreaker
             args:
              name: DELIVERY-SERVICE
              fallbackuri: deliveryServiceFallBack
           - name: RequestRateLimiter
             args:
               '[redis-rate-limiter.replenishRate]': 1
               '[redis-rate-limiter.burstCapacity]': 1
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
           - name: CircuitBreaker
             args:
              name: USER-SERVICE
              fallbackuri: /userServiceFallBack
           - name: RequestRateLimiter
             args:
               '[redis-rate-limiter.replenishRate]': 1
               '[redis-rate-limiter.burstCapacity]': 1
               
okta:
  oauth2:
    issuer: https://dev-53200939.okta.com/oauth2/default
    audience: api://default
    client-id: ${SPRING_OKTA_CLIENT_ID}
    client-secret: ${SPRING_OKTA_CLIENT_SECRET}
    scopes: openid, email, profile, offline_access, internal
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      