server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
          filters:
           - name: CircuitBreaker
             args:
              name: RESTAURANT-SERVICE
              fallbackuri: /restaurantServiceFallBack
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
           - name: CircuitBreaker
             args:
              name: ORDER-SERVICE
              fallbackuri: /orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
           - name: CircuitBreaker
             args:
              name: PAYMENT-SERVICE
              fallbackuri: /paymentServiceFallBack
        - id: DELIVERY-SERVICE
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/deliveries/**
          filters:
           - name: CircuitBreaker
             args:
              name: DELIVERY-SERVICE
              fallbackuri: deliveryServiceFallBack
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      